// <copyright file="Class1Test.Something.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Moles
{
    public partial class Class1Test
    {
[TestMethod]
[PexGeneratedBy(typeof(Class1Test))]
[HostType("Moles")]
public void Something30701()
{
    bool b;
    Class1 s0 = new Class1();
    b = this.Something(s0, default(DateTime));
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(Class1Test))]
[HostType("Moles")]
public void Something913()
{
    bool b;
    Class1 s0 = new Class1();
    b = this.Something(s0, new DateTime(4611686018427387903L & 630822816000000000L, 
                                        (DateTimeKind)(630822816000000000uL >> 62)));
    Assert.AreEqual<bool>(true, b);
    Assert.IsNotNull((object)s0);
}
    }
}
