// <copyright file="ExtensionMethodsTest.Capitalize.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Capitalise
{
    public partial class ExtensionMethodsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void CapitalizeThrowsNullReferenceException720()
{
    string s;
    s = this.Capitalize((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize983()
{
    string s;
    s = this.Capitalize("");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize870()
{
    string s;
    s = this.Capitalize("\0");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize704()
{
    string s;
    s = this.Capitalize(".");
    Assert.AreEqual<string>("_", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize439()
{
    string s;
    s = this.Capitalize("a");
    Assert.AreEqual<string>("A", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize771()
{
    string s;
    s = this.Capitalize("_\0");
    Assert.AreEqual<string>("_", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize790()
{
    string s;
    s = this.Capitalize("__");
    Assert.AreEqual<string>("__", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize669()
{
    string s;
    s = this.Capitalize("aa");
    Assert.AreEqual<string>("Aa", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize32()
{
    string s;
    s = this.Capitalize("_\u8061_");
    Assert.AreEqual<string>("_\u8061_", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize385()
{
    string s;
    s = this.Capitalize("aa.\0");
    Assert.AreEqual<string>("Aa_", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize926()
{
    string s;
    s = this.Capitalize("aa._");
    Assert.AreEqual<string>("Aa__", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize252()
{
    string s;
    s = this.Capitalize("aa..");
    Assert.AreEqual<string>("Aa__", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize688()
{
    string s;
    s = this.Capitalize("aa.a");
    Assert.AreEqual<string>("Aa_A", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize687()
{
    string s;
    s = this.Capitalize("aa.\0\0");
    Assert.AreEqual<string>("Aa_", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionMethodsTest))]
public void Capitalize462()
{
    string s;
    s = this.Capitalize("aa\u8061.");
    Assert.AreEqual<string>("Aa\u8061_", s);
}
    }
}
