// <copyright file="ResizableArrayTTest.Add.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Array
{
    public partial class ResizableArrayTTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ResizableArrayTTest))]
public void Add869()
{
    this.Add<int>(1, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(ResizableArrayTTest))]
[PexRaisedException(typeof(OverflowException))]
public void AddThrowsOverflowException132()
{
    this.Add<int>(int.MinValue, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(ResizableArrayTTest))]
public void Add866()
{
    this.Add<int>(0, 0);
}
    }
}
