// <copyright file="ByHand.TestMethod1.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Dependencies;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Dependencies.Tests.ByHand
{
    public partial class ByHand
    {
[TestMethod]
[PexGeneratedBy(typeof(global::Dependencies.Tests.ByHand.ByHand))]
public void TestMethod1909()
{
    this.TestMethod1(0, Level.Gold, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::Dependencies.Tests.ByHand.ByHand))]
public void TestMethod1848()
{
    this.TestMethod1(0, Level.Silver, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::Dependencies.Tests.ByHand.ByHand))]
public void TestMethod1778()
{
    this.TestMethod1(0, Level.Bronze, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::Dependencies.Tests.ByHand.ByHand))]
[PexRaisedException(typeof(InvalidOperationException))]
public void TestMethod1ThrowsInvalidOperationException782()
{
    this.TestMethod1(0, (Level)3, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(global::Dependencies.Tests.ByHand.ByHand))]
public void TestMethod1945()
{
    this.TestMethod1(0, Level.Bronze, 1001);
}
[TestMethod]
[PexGeneratedBy(typeof(global::Dependencies.Tests.ByHand.ByHand))]
public void TestMethod1654()
{
    this.TestMethod1(0, Level.Bronze, 1000);
}
    }
}
