// <copyright file="CustomerTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Moles
{
    public partial class CustomerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CustomerTest))]
public void Constructor560()
{
    Customer customer;
    customer = this.Constructor(default(DateTime));
    Assert.IsNotNull((object)customer);
    Assert.AreEqual<int>(1, customer.DateOfBirth.Day);
    Assert.AreEqual<DayOfWeek>(DayOfWeek.Monday, customer.DateOfBirth.DayOfWeek);
    Assert.AreEqual<int>(1, customer.DateOfBirth.DayOfYear);
    Assert.AreEqual<int>(0, customer.DateOfBirth.Hour);
    Assert.AreEqual<DateTimeKind>
        (DateTimeKind.Unspecified, customer.DateOfBirth.Kind);
    Assert.AreEqual<int>(0, customer.DateOfBirth.Millisecond);
    Assert.AreEqual<int>(0, customer.DateOfBirth.Minute);
    Assert.AreEqual<int>(1, customer.DateOfBirth.Month);
    Assert.AreEqual<int>(0, customer.DateOfBirth.Second);
    Assert.AreEqual<int>(1, customer.DateOfBirth.Year);
}
    }
}
